source 'https://rubygems.org'

ruby '2.7.2'
gem 'nokogiri', '~> 1.6', '>= 1.6.6.2'
gem 'open-uri', '~> 0.1.0'
gem 'pry', '~> 0.14.1'
gem 'json'
gem 'pp'
gem 'google_drive'
gem 'csv'
gem 'googleauth'